---
name: Evgenii
surname: Kalenkovich
position: "Research Data Specialist"
address: "Bergelson Lab, Duke University"
phone: "+19842602401"
email: "e.kalenkovich@gmail.com"
github: kalenkovich
output:
  vitae::moderncv:
    theme: classic
    keep_tex: yes
headcolor: 009ACD
aboutme: >
  I am a research data specialist in the Bergelson lab where we study language acquisition - babies learning language. 

  I have a background in mathematics and cognitive science, making me well-suited for my role in the lab. Prior to my current position, I led several projects in psycho- and neurolinguistics and worked as a data analyst in the banking industry.

  In my free time, I enjoy reading about the intersection of cognitive computational modeling, developmental psychology, and linguistics, and hope to make contributions to this field in the future. I also enjoy indoor bouldering and introducing friends to the sport.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# Fixes the locale error when knitting with vitae
# From https://community.rstudio.com/t/during-startup-warning-message-setting-lc-ctype-failed-on-windows/21451/3
if (.Platform$OS.type == 'windows') {
  Sys.setlocale(category = 'LC_ALL','English_United States.1250')
} else {
  Sys.setlocale(category = 'LC_ALL','en_US.UTF-8')
}
library(vitae)
library(tibble)
library(readr)
library(glue)
library(dplyr)
library(magrittr)
```

```{r get-data, include = FALSE}
education.data <- read_csv(
  here::here('data', 'education.csv'),
  col_types = cols(.default = "c"))

experience <- read_csv(
  here::here('data', 'experience.csv'),
  col_types = cols(.default = "c")) %>%
  mutate(
    sort_date = replace(end_date, end_date == 'Present','November 2300'),
    sort_date = lubridate::parse_date_time(sort_date, 'b y'),
    when = glue("{start_date} -- {end_date}")) %>%
    # sort_date = lubridate::parse_date_time(start_date, 'b y')) %>%
  arrange(by = desc(sort_date))

jobs.academic <- read_csv(
  here::here('data', 'jobs_academic.csv'),
  col_types = cols(.default = "c"))

jobs.industry <- read_csv(
  here::here('data', 'jobs_industry.csv'),
  col_types = cols(.default = "c"))

skills <- read_csv(
  here::here('data', 'skills.csv'),
  col_types = cols(.default = "c")) %>% 
  group_by(category) %>%
  mutate(skill = paste(skill, collapse = ", ")) %>% 
  ungroup

be <- bibliography_entries(here::here('data', 'from-zotero.bib')) %>%
  ungroup %>%
  arrange(desc(issued)) %>%
  mutate(
    author = vitae:::obj_print_data.list_of_csl_names(author),
    date = vitae:::vec_cast.Date.csl_dates(issued),
    date_string = format(date, '%B %Y'),
    year = format(date, '%Y')) %>%
  as_tibble %>%
  # Highlight my name for vanity purposes
  mutate(author = stringr::str_replace(author,
                                       '([^,]*Kalenkovich[^,]*)',
                                       '\\\\textbf{\\1}')) %>%
  # Escape # in titles
  mutate(title = stringr::str_replace(title, '#', '\\\\#')) %>%
  rename(journal = `container-title`) %T>%
  {filter(., genre == 'Poster') ->> posters2} %T>%
  {filter(., type == 'article-journal') ->> articles.published} %T>%
  {filter(., type %in% c('manuscript', 'report')) ->> articles.in.progress}

training <- read_csv(
  here::here('data', 'training.csv'),
  col_types = cols(.default = "c"))

teaching <- read_csv(here::here("data", "teaching.csv"),
                     col_types = cols(.default = "c"))

extracurricular <- read_csv(
  here::here("data", "extracurricular.csv"),
  col_types = cols(.default = "c"))
```

# Current Position

```{r jobs-current}
experience %>%
  filter(status == 'current') %>%
  detailed_entries(
      when = when,
      # with = glue("\"project name\""),
      what = if_else(is.na(short), glue('{role}'), glue("{role}, {short}")),
      why = details,
      where = glue("\\newline Supervised by {supervisor}, {department}, {company},    {where}"))
```

# Academic Experience

```{r jobs-previous-academic}
experience %>%
  filter(status == 'previous' & type == 'academic') %>%
  detailed_entries(when = when, 
                what = role, 
                with = glue('\\newline {short}'),
                .protect = FALSE)
```

# Non-Academic Jobs

```{r jobs-non-academic}
experience %>%
  filter(type == 'non-academic') %>%
  detailed_entries(
    when = when,
    with = if_else(is.na(department), NA_character_, department),
    what = role,
    where = glue("{company}, {where}"),
    why = details)

```

# Education

```{r show-education}
education.data %>%
  detailed_entries(
    what = title,
    when = glue::glue("{start_date} - {end_date}"),
    with = glue::glue("{university}, {department}"),
    where = city
  )
```

# Publications

## Published

```{r articles-published}
articles.published %>%
  detailed_entries(
    what = author,
    when = as.character(year),
    with = title,
    where = journal,
    .protect = FALSE
  )
```
## In progress

```{r articles-in-progress}
articles.in.progress %>%
  detailed_entries(
    what = author,
    with = title,
    # In Zotero, the comment is under "type". No idea how this became "genre".
    when = genre,
    .protect = FALSE
  )
```

# Posters

```{r posters2}
posters2 %>%
  arrange(desc(issued)) %>%
  detailed_entries(
    what = author,
    when = date_string,
    with = title,
    where = glue('{event}, {`event-place`}'),
    .protect = FALSE
  )
```

# Teaching

## University courses

```{r teaching-uni}
teaching %>%
  filter(type == "University course")  %>%
  detailed_entries(what = with, when = when, with = what, where = where, why = why)
```

## Mini courses

```{r teaching-summer-schools}
teaching %>%
  filter(type == "Mini course") %>%
  detailed_entries(what = with, when = when, with = what, where = where, why = why)
```

# Training

```{r training, results='asis'}
training.types <- unique(training$type)

for (training.type in training.types) {
  cat('##', training.type, '\n')

  training %>%
    filter(type == training.type) %>%
    arrange(desc(when)) %>%
    detailed_entries(what = glue("{with}, {where}"), 
                     where = when,
                     why = why, 
                     with = what,
                     .protect = FALSE) %>%
    knitr::knit_print() %>%
    cat


  cat('\n\n')
}
```


# Extracurricular activity

```{r extracurricular}
extracurricular %>%
  detailed_entries(with = what, what = when, why = why)
```

\pagebreak


# Skills

```{r}
skills %>% 
  detailed_entries(what = skill, with = category)
```



