name: render-cv
on: [workflow_dispatch]
jobs:
  render-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - run: Rscript -e 'print(R.Version())'
      
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.12'      
      - run: pandoc --version
