name: render-cv
on: [workflow_dispatch]
jobs:
  render-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: git branch --show-current
    
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - run: Rscript -e 'print(R.Version())'
      
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.12'      
      - run: pandoc --version
      
      - uses: r-lib/actions/setup-tinytex@v1
      - run: tlmgr --version
      
      - name: Install libcurl-dev for r package curl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Render cv.Rmd
        env:
          ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
        run: |
          bash render.sh
          FILE=cv/cv.pdf
          if [ -f "$FILE" ]; then
              echo "$FILE exists."
          else 
              echo "$FILE does not exist."
          fi
          FILE=cv/cv.tex
          if [ -f "$FILE" ]; then
              echo "$FILE exists."
          else 
              echo "$FILE does not exist."
          fi
          
